<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<AssemblyName>MDL_Launcher</AssemblyName>
		<Version>0.2.2-beta</Version>
		<FileVersion>0.2.2-beta</FileVersion>

		<ApplicationIcon>icon.ico</ApplicationIcon>
		<Company>Color_Garden</Company>
		<Product>MDL启动器</Product>
		<Copyright>Copyright © 2026</Copyright>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Assets\itch_logo.png" />
	  <None Remove="Assets\steam_logo.png" />
	  <None Remove="Fonts\font.ttf" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Assets\itch_logo.png" />
	  <Resource Include="Assets\steam_logo.png" />
	  <Resource Include="Fonts\font.ttf" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Lang\zh-CN.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Lang\en-US.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.*" />
	</ItemGroup>
</Project>