/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc_backend_sdl_jni_SDL */

#ifndef _Included_arc_backend_sdl_jni_SDL
#define _Included_arc_backend_sdl_jni_SDL
#ifdef __cplusplus
extern "C" {
#endif
#undef arc_backend_sdl_jni_SDL_SDL_INIT_TIMER
#define arc_backend_sdl_jni_SDL_SDL_INIT_TIMER 1L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_AUDIO
#define arc_backend_sdl_jni_SDL_SDL_INIT_AUDIO 16L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_VIDEO
#define arc_backend_sdl_jni_SDL_SDL_INIT_VIDEO 32L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_JOYSTICK
#define arc_backend_sdl_jni_SDL_SDL_INIT_JOYSTICK 512L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_HAPTIC
#define arc_backend_sdl_jni_SDL_SDL_INIT_HAPTIC 4096L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_GAMECONTROLLER
#define arc_backend_sdl_jni_SDL_SDL_INIT_GAMECONTROLLER 8192L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_EVENTS
#define arc_backend_sdl_jni_SDL_SDL_INIT_EVENTS 16384L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_NOPARACHUTE
#define arc_backend_sdl_jni_SDL_SDL_INIT_NOPARACHUTE 1048576L
#undef arc_backend_sdl_jni_SDL_SDL_INIT_EVERYTHING
#define arc_backend_sdl_jni_SDL_SDL_INIT_EVERYTHING 29233L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_FULLSCREEN
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_FULLSCREEN 1L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_OPENGL
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_OPENGL 2L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_SHOWN
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_SHOWN 4L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_HIDDEN
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_HIDDEN 8L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_BORDERLESS
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_BORDERLESS 16L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_RESIZABLE
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_RESIZABLE 32L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_MINIMIZED
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_MINIMIZED 64L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_MAXIMIZED
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_MAXIMIZED 128L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_INPUT_GRABBED
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_INPUT_GRABBED 256L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_INPUT_FOCUS
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_INPUT_FOCUS 512L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_MOUSE_FOCUS
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_MOUSE_FOCUS 1024L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_FULLSCREEN_DESKTOP
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_FULLSCREEN_DESKTOP 4097L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_FOREIGN
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_FOREIGN 2048L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_ALLOW_HIGHDPI
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_ALLOW_HIGHDPI 8192L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOW_MOUSE_CAPTURE
#define arc_backend_sdl_jni_SDL_SDL_WINDOW_MOUSE_CAPTURE 16384L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_NONE
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_NONE 0L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_SHOWN
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_SHOWN 1L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_HIDDEN
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_HIDDEN 2L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_EXPOSED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_EXPOSED 3L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_MOVED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_MOVED 4L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_RESIZED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_RESIZED 5L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_SIZE_CHANGED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_SIZE_CHANGED 6L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_MINIMIZED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_MINIMIZED 7L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_MAXIMIZED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_MAXIMIZED 8L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_RESTORED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_RESTORED 9L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_ENTER
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_ENTER 10L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_LEAVE
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_LEAVE 11L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_FOCUS_GAINED
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_FOCUS_GAINED 12L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_FOCUS_LOST
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_FOCUS_LOST 13L
#undef arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_CLOSE
#define arc_backend_sdl_jni_SDL_SDL_WINDOWEVENT_CLOSE 14L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_ARROW
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_ARROW 0L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_IBEAM
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_IBEAM 1L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_WAIT
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_WAIT 2L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_CROSSHAIR
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_CROSSHAIR 3L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_WAITARROW
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_WAITARROW 4L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZENWSE
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZENWSE 5L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZENESW
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZENESW 6L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZEWE
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZEWE 7L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZENS
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZENS 8L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZEALL
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_SIZEALL 9L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_NO
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_NO 10L
#undef arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_HAND
#define arc_backend_sdl_jni_SDL_SDL_SYSTEM_CURSOR_HAND 11L
#undef arc_backend_sdl_jni_SDL_SDL_NUM_SYSTEM_CURSORS
#define arc_backend_sdl_jni_SDL_SDL_NUM_SYSTEM_CURSORS 12L
#undef arc_backend_sdl_jni_SDL_SDL_MESSAGEBOX_ERROR
#define arc_backend_sdl_jni_SDL_SDL_MESSAGEBOX_ERROR 16L
#undef arc_backend_sdl_jni_SDL_SDL_MESSAGEBOX_WARNING
#define arc_backend_sdl_jni_SDL_SDL_MESSAGEBOX_WARNING 32L
#undef arc_backend_sdl_jni_SDL_SDL_MESSAGEBOX_INFORMATION
#define arc_backend_sdl_jni_SDL_SDL_MESSAGEBOX_INFORMATION 64L
#undef arc_backend_sdl_jni_SDL_SDL_BUTTON_LEFT
#define arc_backend_sdl_jni_SDL_SDL_BUTTON_LEFT 1L
#undef arc_backend_sdl_jni_SDL_SDL_BUTTON_MIDDLE
#define arc_backend_sdl_jni_SDL_SDL_BUTTON_MIDDLE 2L
#undef arc_backend_sdl_jni_SDL_SDL_BUTTON_RIGHT
#define arc_backend_sdl_jni_SDL_SDL_BUTTON_RIGHT 3L
#undef arc_backend_sdl_jni_SDL_SDL_BUTTON_X1
#define arc_backend_sdl_jni_SDL_SDL_BUTTON_X1 4L
#undef arc_backend_sdl_jni_SDL_SDL_BUTTON_X2
#define arc_backend_sdl_jni_SDL_SDL_BUTTON_X2 5L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_QUIT
#define arc_backend_sdl_jni_SDL_SDL_EVENT_QUIT 0L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_WINDOW
#define arc_backend_sdl_jni_SDL_SDL_EVENT_WINDOW 1L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_MOUSE_MOTION
#define arc_backend_sdl_jni_SDL_SDL_EVENT_MOUSE_MOTION 2L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_MOUSE_BUTTON
#define arc_backend_sdl_jni_SDL_SDL_EVENT_MOUSE_BUTTON 3L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_MOUSE_WHEEL
#define arc_backend_sdl_jni_SDL_SDL_EVENT_MOUSE_WHEEL 4L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_KEYBOARD
#define arc_backend_sdl_jni_SDL_SDL_EVENT_KEYBOARD 5L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_TEXT_INPUT
#define arc_backend_sdl_jni_SDL_SDL_EVENT_TEXT_INPUT 6L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_TEXT_EDIT
#define arc_backend_sdl_jni_SDL_SDL_EVENT_TEXT_EDIT 8L
#undef arc_backend_sdl_jni_SDL_SDL_EVENT_OTHER
#define arc_backend_sdl_jni_SDL_SDL_EVENT_OTHER 7L
#undef arc_backend_sdl_jni_SDL_SDL_GL_RED_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_RED_SIZE 0L
#undef arc_backend_sdl_jni_SDL_SDL_GL_GREEN_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_GREEN_SIZE 1L
#undef arc_backend_sdl_jni_SDL_SDL_GL_BLUE_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_BLUE_SIZE 2L
#undef arc_backend_sdl_jni_SDL_SDL_GL_ALPHA_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_ALPHA_SIZE 3L
#undef arc_backend_sdl_jni_SDL_SDL_GL_BUFFER_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_BUFFER_SIZE 4L
#undef arc_backend_sdl_jni_SDL_SDL_GL_DOUBLEBUFFER
#define arc_backend_sdl_jni_SDL_SDL_GL_DOUBLEBUFFER 5L
#undef arc_backend_sdl_jni_SDL_SDL_GL_DEPTH_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_DEPTH_SIZE 6L
#undef arc_backend_sdl_jni_SDL_SDL_GL_STENCIL_SIZE
#define arc_backend_sdl_jni_SDL_SDL_GL_STENCIL_SIZE 7L
#undef arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_MAJOR_VERSION
#define arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_MAJOR_VERSION 17L
#undef arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_MINOR_VERSION
#define arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_MINOR_VERSION 18L
#undef arc_backend_sdl_jni_SDL_SDL_GL_MULTISAMPLEBUFFERS
#define arc_backend_sdl_jni_SDL_SDL_GL_MULTISAMPLEBUFFERS 13L
#undef arc_backend_sdl_jni_SDL_SDL_GL_MULTISAMPLESAMPLES
#define arc_backend_sdl_jni_SDL_SDL_GL_MULTISAMPLESAMPLES 14L
#undef arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_PROFILE_CORE
#define arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_PROFILE_CORE 1L
#undef arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_PROFILE_COMPATIBILITY
#define arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_PROFILE_COMPATIBILITY 2L
#undef arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_PROFILE_MASK
#define arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_PROFILE_MASK 21L
#undef arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_FLAGS
#define arc_backend_sdl_jni_SDL_SDL_GL_CONTEXT_FLAGS 20L
/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_Init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1Init
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_InitSubSystem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1InitSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_QuitSubSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1QuitSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_WasInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1WasInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_Quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1Quit
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetHint
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetHint
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetCompiledVersion
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetCompiledVersion
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetVersion
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetVersion
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetError
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetClipboardText
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetClipboardText
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetClipboardText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetClipboardText
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_CreateWindow
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1CreateWindow
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_DestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1DestroyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowIcon
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowIcon
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_RestoreWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1RestoreWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_MaximizeWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1MaximizeWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_MinimizeWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1MinimizeWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowFullscreen
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowFullscreen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowBordered
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowBordered
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowPosition
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowPosition
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetWindowDisplayIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetWindowDisplayIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetDisplayUsableBounds
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetDisplayUsableBounds
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetDisplayBounds
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetDisplayBounds
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetCurrentDisplayMode
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetCurrentDisplayMode
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetDesktopDisplayMode
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetDesktopDisplayMode
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowAlwaysOnTop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowAlwaysOnTop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetNumVideoDisplays
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetNumVideoDisplays
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GetWindowFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GetWindowFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetWindowTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetWindowTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_CreateRGBSurfaceFrom
 * Signature: (Ljava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1CreateRGBSurfaceFrom
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_CreateColorCursor
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1CreateColorCursor
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_CreateSystemCursor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1CreateSystemCursor
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetCursor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetCursor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_FreeCursor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1FreeCursor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_FreeSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1FreeSurface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_ShowSimpleMessageBox
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1ShowSimpleMessageBox
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_StartTextInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1StartTextInput
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_StopTextInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1StopTextInput
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_SetTextInputRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1SetTextInputRect
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_IsTextInputActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1IsTextInputActive
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_PollEvent
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1PollEvent
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GL_SetAttribute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GL_1SetAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GL_ExtensionSupported
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GL_1ExtensionSupported
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GL_CreateContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GL_1CreateContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GL_SetSwapInterval
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GL_1SetSwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GL_SwapWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GL_1SwapWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_backend_sdl_jni_SDL
 * Method:    SDL_GL_GetDrawableSize
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDL_SDL_1GL_1GetDrawableSize
  (JNIEnv *, jclass, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
