/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc_backend_sdl_jni_SDLGL */

#ifndef _Included_arc_backend_sdl_jni_SDLGL
#define _Included_arc_backend_sdl_jni_SDLGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    init
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_init
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBlendFunc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearDepthf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearDepthf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glColorMask
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCompressedTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCompressedTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCopyTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCopyTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCullFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDepthFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDepthMask
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDepthRangef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDepthRangef
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawElements
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawElements__IIILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFinish
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFlush
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenTexture
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetError
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetIntegerv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glPixelStorei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glPolygonOffset
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glStencilFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glStencilMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glStencilOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glAttachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glAttachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindAttribLocation
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindAttribLocation
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindFramebuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindRenderbuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindRenderbuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBlendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBlendColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBlendEquation
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBlendEquationSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBlendEquationSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBufferData
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBufferData
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBufferSubData
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBufferSubData
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCheckFramebufferStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glCheckFramebufferStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCompileShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCompileShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCreateProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glCreateProgram
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCreateShader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glCreateShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteFramebuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteRenderbuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDetachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDetachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDisableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDisableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawElements__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glEnableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glEnableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFramebufferRenderbuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFramebufferRenderbuffer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFramebufferTexture2D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFramebufferTexture2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenBuffer
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenerateMipmap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenerateMipmap
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenFramebuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenFramebuffer
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenRenderbuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenRenderbuffer
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetActiveAttrib
 * Signature: (IILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetActiveAttrib
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetActiveUniform
 * Signature: (IILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetActiveUniform
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetAttribLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetAttribLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetBooleanv
 * Signature: (ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetBooleanv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetBufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetBufferParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetFloatv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetFramebufferAttachmentParameteriv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetFramebufferAttachmentParameteriv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetProgramiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetProgramiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetProgramInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetProgramInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetRenderbufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetRenderbufferParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetShaderiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetShaderiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetShaderInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetShaderInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetShaderPrecisionFormat
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetShaderPrecisionFormat
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetTexParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetTexParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetUniformfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetUniformfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetUniformiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetUniformiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetUniformLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetUniformLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetVertexAttribfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetVertexAttribfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetVertexAttribiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetVertexAttribiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsFramebuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsProgram
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsRenderbuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsShader
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glLinkProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glLinkProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glReleaseShaderCompiler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glReleaseShaderCompiler
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glRenderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glRenderbufferStorage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glSampleCoverage
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glShaderSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glShaderSource
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glStencilFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glStencilFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glStencilMaskSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glStencilMaskSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glStencilOpSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glStencilOpSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform2fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform2fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform2fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform2fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform2i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform2i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform2iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform2iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform2iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform2iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix2fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix2fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix2fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix2fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix3fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix3fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix3fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix3fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix4fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix4fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix4fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix4fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUseProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glValidateProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glValidateProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib1fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib1fv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib2fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib2fv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib3fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib3fv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttrib4fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttrib4fv
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttribPointer
 * Signature: (IIIZILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttribPointer__IIIZILjava_lang_Object_2
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttribPointer__IIIZII
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glReadBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glReadBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawRangeElements
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawRangeElements__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawRangeElements
 * Signature: (IIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawRangeElements__IIIIILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexImage3D
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexImage3D__IIIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexImage3D
 * Signature: (IIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexImage3D__IIIIIIIIILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexSubImage3D
 * Signature: (IIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexSubImage3D__IIIIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTexSubImage3D
 * Signature: (IIIIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTexSubImage3D__IIIIIIIIIILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCopyTexSubImage3D
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCopyTexSubImage3D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenQueries
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenQueries
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteQueries
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteQueries
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsQuery
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsQuery
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBeginQuery
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBeginQuery
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glEndQuery
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glEndQuery
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetQueryiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetQueryiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetQueryObjectuiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetQueryObjectuiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUnmapBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glUnmapBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetBufferPointerv
 * Signature: (II)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetBufferPointerv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawBuffers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix2x3fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix2x3fv
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix3x2fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix3x2fv
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix2x4fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix2x4fv
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix4x2fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix4x2fv
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix3x4fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix3x4fv
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformMatrix4x3fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformMatrix4x3fv
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBlitFramebuffer
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBlitFramebuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glRenderbufferStorageMultisample
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glRenderbufferStorageMultisample
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFramebufferTextureLayer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFramebufferTextureLayer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glFlushMappedBufferRange
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glFlushMappedBufferRange
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindVertexArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindVertexArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteVertexArrays
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteVertexArrays
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenVertexArrays
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenVertexArrays
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsVertexArray
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsVertexArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBeginTransformFeedback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBeginTransformFeedback
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glEndTransformFeedback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glEndTransformFeedback
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindBufferRange
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindBufferRange
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindBufferBase
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindBufferBase
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glTransformFeedbackVaryings
 * Signature: (I[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glTransformFeedbackVaryings
  (JNIEnv *, jclass, jint, jobjectArray, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttribIPointer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttribIPointer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetVertexAttribIiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetVertexAttribIiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetVertexAttribIuiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetVertexAttribIuiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttribI4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttribI4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttribI4ui
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttribI4ui
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetUniformuiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetUniformuiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetFragDataLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetFragDataLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform1uiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform1uiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform3uiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform3uiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniform4uiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniform4uiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearBufferiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearBufferiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearBufferuiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearBufferuiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearBufferfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearBufferfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glClearBufferfi
 * Signature: (IIFI)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glClearBufferfi
  (JNIEnv *, jclass, jint, jint, jfloat, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetStringi
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetStringi
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glCopyBufferSubData
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glCopyBufferSubData
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetUniformIndices
 * Signature: (I[Ljava/lang/String;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetUniformIndices
  (JNIEnv *, jclass, jint, jobjectArray, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetActiveUniformsiv
 * Signature: (IILjava/nio/IntBuffer;ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetActiveUniformsiv
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetUniformBlockIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetUniformBlockIndex
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetActiveUniformBlockiv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetActiveUniformBlockiv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetActiveUniformBlockName
 * Signature: (IILjava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetActiveUniformBlockName
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glUniformBlockBinding
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glUniformBlockBinding
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawArraysInstanced
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawArraysInstanced
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDrawElementsInstanced
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDrawElementsInstanced
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetInteger64v
 * Signature: (ILjava/nio/LongBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetInteger64v
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetBufferParameteri64v
 * Signature: (IILjava/nio/LongBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetBufferParameteri64v
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenSamplers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenSamplers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteSamplers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteSamplers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsSampler
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsSampler
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindSampler
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindSampler
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glSamplerParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glSamplerParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glSamplerParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glSamplerParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glSamplerParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glSamplerParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glSamplerParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glSamplerParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetSamplerParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetSamplerParameteriv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGetSamplerParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGetSamplerParameterfv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glVertexAttribDivisor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glVertexAttribDivisor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glBindTransformFeedback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glBindTransformFeedback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glDeleteTransformFeedbacks
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glDeleteTransformFeedbacks
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glGenTransformFeedbacks
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glGenTransformFeedbacks
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glIsTransformFeedback
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_backend_sdl_jni_SDLGL_glIsTransformFeedback
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glPauseTransformFeedback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glPauseTransformFeedback
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glResumeTransformFeedback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glResumeTransformFeedback
  (JNIEnv *, jclass);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glProgramParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glProgramParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glInvalidateFramebuffer
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glInvalidateFramebuffer
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     arc_backend_sdl_jni_SDLGL
 * Method:    glInvalidateSubFramebuffer
 * Signature: (IILjava/nio/IntBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_arc_backend_sdl_jni_SDLGL_glInvalidateSubFramebuffer
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
