/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc_graphics_Pixmap */

#ifndef _Included_arc_graphics_Pixmap
#define _Included_arc_graphics_Pixmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_graphics_Pixmap
 * Method:    loadJni
 * Signature: ([J[BII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_arc_graphics_Pixmap_loadJni
  (JNIEnv *, jclass, jlongArray, jbyteArray, jint, jint);

/*
 * Class:     arc_graphics_Pixmap
 * Method:    createJni
 * Signature: ([JII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_arc_graphics_Pixmap_createJni
  (JNIEnv *, jclass, jlongArray, jint, jint);

/*
 * Class:     arc_graphics_Pixmap
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_graphics_Pixmap_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_graphics_Pixmap
 * Method:    getFailureReason
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_graphics_Pixmap_getFailureReason
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
