/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc_audio_Soloud */

#ifndef _Included_arc_audio_Soloud
#define _Included_arc_audio_Soloud
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_audio_Soloud
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_init
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_deinit
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    backendString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arc_audio_Soloud_backendString
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    backendId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_backendId
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    backendChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_backendChannels
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    backendSamplerate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_backendSamplerate
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    backendBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_backendBufferSize
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_version
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    activeVoiceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_activeVoiceCount
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    stopAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_stopAll
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    pauseAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_pauseAll
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    biquadSet
 * Signature: (JIFF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_biquadSet
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    echoSet
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_echoSet
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    lofiSet
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_lofiSet
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    flangerSet
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_flangerSet
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    waveShaperSet
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_waveShaperSet
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    bassBoostSet
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_bassBoostSet
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    robotizeSet
 * Signature: (JFI)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_robotizeSet
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    freeverbSet
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_freeverbSet
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterBiquad
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterBiquad
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterEcho
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterEcho
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterLofi
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterLofi
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterFlanger
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterFlanger
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterBassBoost
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterBassBoost
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterWaveShaper
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterWaveShaper
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterRobotize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterRobotize
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterFreeverb
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_filterFreeverb
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    setGlobalFilter
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_setGlobalFilter
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterFade
 * Signature: (IIIFF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_filterFade
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    filterSet
 * Signature: (IIIF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_filterSet
  (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    busNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_busNew
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    wavLoad
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_wavLoad
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    idSeek
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idSeek
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    idVolume
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idVolume
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    idGetVolume
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_arc_audio_Soloud_idGetVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    idPan
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idPan
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    idPitch
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idPitch
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    idPause
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idPause
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    idGetPause
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_audio_Soloud_idGetPause
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    idProtected
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idProtected
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    idStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    idLooping
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_idLooping
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    idGetLooping
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_audio_Soloud_idGetLooping
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    idPosition
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_arc_audio_Soloud_idPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    idValid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_arc_audio_Soloud_idValid
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    streamLoad
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_arc_audio_Soloud_streamLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     arc_audio_Soloud
 * Method:    streamLength
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_arc_audio_Soloud_streamLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    wavLength
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_arc_audio_Soloud_wavLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceInaudible
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceInaudible
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourcePlay
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_sourcePlay__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_sourceCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourcePlay
 * Signature: (JFFFZ)I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_sourcePlay__JFFFZ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourcePlayBus
 * Signature: (JJFFFZ)I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_sourcePlayBus
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourcePriority
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourcePriority
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceMinConcurrentInterrupt
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceMinConcurrentInterrupt
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceMaxConcurrent
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceMaxConcurrent
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceConcurrentGroup
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceConcurrentGroup
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceLoop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceLoop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceSingleInstance
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceSingleInstance
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    sourceFilter
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_arc_audio_Soloud_sourceFilter
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     arc_audio_Soloud
 * Method:    pauseDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_pauseDevice
  (JNIEnv *, jclass);

/*
 * Class:     arc_audio_Soloud
 * Method:    resumeDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_arc_audio_Soloud_resumeDevice
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
