/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arc_util_Buffers */

#ifndef _Included_arc_util_Buffers
#define _Included_arc_util_Buffers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arc_util_Buffers
 * Method:    freeMemory
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_freeMemory
  (JNIEnv *, jclass, jobject);

/*
 * Class:     arc_util_Buffers
 * Method:    newDisposableByteBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_arc_util_Buffers_newDisposableByteBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    getBufferAddress
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_arc_util_Buffers_getBufferAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     arc_util_Buffers
 * Method:    clear
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_clear
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    copyJni
 * Signature: ([FLjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_copyJni___3FLjava_nio_Buffer_2II
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    copyJni
 * Signature: ([BILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_copyJni___3BILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jint, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    copyJni
 * Signature: ([SILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_copyJni___3SILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jshortArray, jint, jobject, jint, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    copyJni
 * Signature: ([IILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_copyJni___3IILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jintArray, jint, jobject, jint, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    copyJni
 * Signature: ([FILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_copyJni___3FILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jfloatArray, jint, jobject, jint, jint);

/*
 * Class:     arc_util_Buffers
 * Method:    copyJni
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_arc_util_Buffers_copyJni__Ljava_nio_Buffer_2ILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
